#ifndef AXTLS_LOGGING_H
#define AXTLS_LOGGING_H
#include "application.h"
#if defined(CONFIG_DEBUG) && defined(CONFIG_PLATFORM_PARTICLE)

#if CONFIG_DEBUG_MODE == DEBUG_MODE_LOGGER

Logger CONFIG_DEBUG_LOGGER_NAME(CONFIG_DEBUG_LOGGER_CATEGORY);
#define debug_tls( fmt, ... ) CONFIG_DEBUG_LOGGER_NAME.CONFIG_DEBUG_LOGGER_LEVEL(fmt, ##__VA_ARGS__)

#endif /* LOGGER */

#if CONFIG_DEBUG_MODE == DEBUG_MODE_SERIAL

CONFIG_DEBUG_SERIAL_CLASS *CONFIG_DEBUG_SERIAL_PTR = &CONFIG_DEBUG_SERIAL_CHANNEL;
#define debug_tls( fmt, ... ) CONFIG_DEBUG_SERIAL_PTR->println(fmt, ##__VA_ARGS__)

#endif /* SERIAL */

#endif /* CONFIG_DEBUG */

#endif /* AXTLS_LOGGING_H */
